"""
Markdown Report Generator
Generates human-friendly Markdown reports with collapsible sections.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from .base_report import BaseReportGenerator


class MarkdownReportGenerator(BaseReportGenerator):
    """Generates readable Markdown reports."""

    name = "markdown"
    extension = ".md"
    description = "Human-friendly Markdown report"

    def generate(
        self, target: str, results: Dict[str, Any], filename: Optional[str] = None
    ) -> str:
        """Generate Markdown report file."""
        filepath = self._get_filepath(target, filename)

        lines = []
        lines.append(f"# OmniSight AI - OSINT Report")
        lines.append(f"")
        lines.append(f"**Target:** `{target}`")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}")
        lines.append(f"**Tool:** [OmniSight AI v2.0](https://github.com/AliZafar780/ai-osint-tool)")
        lines.append(f"")
        lines.append(f"---")
        lines.append(f"")

        # Table of Contents
        lines.append(f"## Table of Contents")
        lines.append(f"")
        for module_name in results.keys():
            anchor = module_name.lower().replace(" ", "-").replace("_", "-")
            lines.append(f"- [{module_name}](#{anchor})")
        lines.append(f"")
        lines.append(f"---")
        lines.append(f"")

        for module_name, module_result in results.items():
            anchor = module_name.lower().replace(" ", "-").replace("_", "-")
            lines.append(f"## {module_name}")
            lines.append(f"")
            lines.append(f"<a id=\"{anchor}\"></a>")
            lines.append(f"")

            if isinstance(module_result, dict):
                status = module_result.get("status", "completed")
                error = module_result.get("error")
                duration = module_result.get("duration_ms")
                data = module_result.get("data", module_result)

                lines.append(f"- **Status:** {status}")
                if duration:
                    lines.append(f"- **Duration:** {duration:.0f}ms")
                if error:
                    lines.append(f"- **Warning/Error:** {error}")
                lines.append(f"")

                self._format_data(lines, data)
            else:
                self._format_data(lines, module_result)

            lines.append(f"---")
            lines.append(f"")

        # Footer
        lines.append(f"")
        lines.append(f"---")
        lines.append(f"*Report generated by [OmniSight AI](https://github.com/AliZafar780/ai-osint-tool)*")
        lines.append(f"")

        content = "\n".join(lines)

        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
        except OSError as e:
            raise IOError(f"Failed to write Markdown report: {e}")

        return filepath

    def _format_data(self, lines: List[str], data: Any, indent: int = 0):
        """Recursively format data as Markdown."""
        prefix = "  " * indent
        bullet = "- " if indent == 0 else "  - "

        if isinstance(data, dict):
            for key, value in data.items():
                if key in ("error", "_error") and value:
                    lines.append(f"{prefix}> ⚠️ **{key}:** {value}")
                    continue
                if value is None or value == "" or value == [] or value == {}:
                    continue
                if isinstance(value, (dict, list)):
                    lines.append(f"{prefix}**{key}:**")
                    self._format_data(lines, value, indent + 1)
                else:
                    val_str = str(value)[:500]
                    if isinstance(value, bool):
                        val_str = "✅ Yes" if value else "❌ No"
                    lines.append(f"{prefix}{bullet}**{key}:** {val_str}")
        elif isinstance(data, list):
            for item in data:
                if isinstance(item, (dict, list)):
                    self._format_data(lines, item, indent + 1)
                else:
                    lines.append(f"{prefix}{bullet}{str(item)[:500]}")
        elif data:
            lines.append(f"{prefix}{str(data)[:1000]}")
